boot:
	@cd simple-local-wiki && npx --verbose -y @tuxounet-k2/cli@latest ./k2.inventory.yaml apply

dev-apply: 
	@cd simple-local-wiki && node ../../../k2/dist/index.js ./k2.inventory.yaml apply

dev-clean:
	@cd simple-local-wiki && node ../../../k2/dist/index.js ./k2.inventory.yaml clean
